### ISSUE TITLE
Forward live call

### ISSUE THREAD

**Issue by kmligue** [plivo/plivo-web-sdk-example#8]
Is there a way to transfer a live call using this web sdk? For instance, i receive a call and then the caller wants to transfer/call to another number.

**Comment by cachrisman** [comment]
@kmligue You can't transfer directly from the web sdk to another number. To achieve this capability, you need to have the client side js which is using the Plivo web sdk make a request to your server which is serving up the webpage and then from the web server make a request to [Plivo's Transfer API](https://www.plivo.com/docs/api/call/#transfer-a-call) to transfer the call. You can also see [this getting started page](https://www.plivo.com/docs/getting-started/transfer-api/) for more details.

You can't make a Plivo API request directly from client side JS because your Plivo credentials would be exposed to anyone visiting the webpage so we don't allow that.
